import { useState, useEffect } from 'react';

const GLASS = {
  blur: '0px',
  scrim: 'rgba(15, 23, 42, 0.02)',
  shadow: '0 10px 24px rgba(15, 23, 42, 0.10)',
  textShadow: 'none',
};

export const THEMES = {
  ghost: {
    id: 'ghost',
    period: 'ghost',
    label: 'Ghost Protocol',
    gradient: 'linear-gradient(135deg, #09090b 0%, #030712 100%)',
    bgColor: '#030712',
    surfaceColor: '#09090b',
    cardColor: '#09090b',
    inputBg: '#09090b',
    headerBg: 'rgba(9, 9, 11, 0.95)',
    navBg: 'rgba(9, 9, 11, 0.98)',
    glassBg: 'rgba(9, 9, 11, 0.6)',
    glassBorder: '#00f0ff',
    orbA: 'rgba(0, 240, 255, 0.15)',
    orbB: 'rgba(0, 255, 170, 0.1)',
    text: '#00f0ff',
    muted: '#4b5563',
    secondaryText: '#00ffaa',
    accentColor: '#00f0ff',
    accentLight: '#00ffaa',
    accentFg: '#000000',
    border: 'rgba(0, 240, 255, 0.3)',
    borderM: '#00f0ff',
    red: '#ff003c',
    green: '#00ffaa',
    blue: '#00f0ff',
    purple: '#a855f7',
    ...GLASS,
  },
  dark: {
    id: 'dark',
    period: 'dark',
    label: 'Midnight Dark',
    gradient: 'linear-gradient(180deg, #0f172a 0%, #020617 100%)',
    bgColor: '#020617',
    surfaceColor: '#0f172a',
    cardColor: '#1e293b',
    inputBg: '#1e293b',
    headerBg: 'rgba(15, 23, 42, 0.96)',
    navBg: 'rgba(15, 23, 42, 0.98)',
    glassBg: '#1e293b',
    glassBorder: '#334155',
    orbA: 'transparent',
    orbB: 'transparent',
    text: '#f8fafc',
    muted: '#94a3b8',
    secondaryText: '#cbd5e1',
    accentColor: '#3b82f6',
    accentLight: '#60a5fa',
    accentFg: '#ffffff',
    border: '#334155',
    borderM: '#3b82f6',
    red: '#ef4444',
    green: '#10b981',
    blue: '#3b82f6',
    purple: '#8b5cf6',
    ...GLASS,
  },
  oled: {
    id: 'oled',
    period: 'oled',
    label: 'AMOLED Black',
    gradient: 'none',
    bgColor: '#000000',
    surfaceColor: '#09090b',
    cardColor: '#000000',
    inputBg: '#09090b',
    headerBg: 'rgba(0, 0, 0, 0.96)',
    navBg: 'rgba(0, 0, 0, 0.98)',
    glassBg: '#000000',
    glassBorder: '#27272a',
    orbA: 'transparent',
    orbB: 'transparent',
    text: '#ffffff',
    muted: '#a1a1aa',
    secondaryText: '#d4d4d8',
    accentColor: '#f43f5e',
    accentLight: '#fb7185',
    accentFg: '#ffffff',
    border: '#27272a',
    borderM: '#f43f5e',
    red: '#f43f5e',
    green: '#10b981',
    blue: '#3b82f6',
    purple: '#a855f7',
    ...GLASS,
  },
  cyberpunk: {
    id: 'cyberpunk',
    period: 'cyberpunk',
    label: 'Cyberpunk',
    gradient: 'linear-gradient(135deg, #2e021d 0%, #0d0221 100%)',
    bgColor: '#0d0221',
    surfaceColor: '#1a052b',
    cardColor: '#2e021d',
    inputBg: '#1a052b',
    headerBg: 'rgba(13, 2, 33, 0.96)',
    navBg: 'rgba(13, 2, 33, 0.98)',
    glassBg: 'rgba(46, 2, 29, 0.7)',
    glassBorder: '#ff003c',
    orbA: 'rgba(255, 0, 60, 0.2)',
    orbB: 'rgba(0, 240, 255, 0.2)',
    text: '#00f0ff',
    muted: '#fce205',
    secondaryText: '#ff003c',
    accentColor: '#ff003c',
    accentLight: '#ff4d79',
    accentFg: '#ffffff',
    border: '#ff003c',
    borderM: '#00f0ff',
    red: '#ff003c',
    green: '#00ff00',
    blue: '#00f0ff',
    purple: '#b026ff',
    ...GLASS,
  }
};

export const getSelectedTheme = () => {
  const saved = localStorage.getItem('crimetrack_theme') || 'ghost';
  return THEMES[saved] || THEMES.ghost;
};

export const themeToCssVars = (theme) => ({
  '--ct-bg': theme.bgColor,
  '--ct-surface': theme.surfaceColor,
  '--ct-card': theme.glassBg,
  '--ct-input-bg': theme.inputBg,
  '--ct-header-bg': theme.headerBg,
  '--ct-nav-bg': theme.navBg,
  '--ct-text': theme.text,
  '--ct-muted': theme.muted,
  '--ct-secondary': theme.secondaryText,
  '--ct-accent': theme.accentColor,
  '--ct-accent-light': theme.accentLight,
  '--ct-accent-fg': theme.accentFg,
  '--ct-border': theme.border,
  '--ct-border-m': theme.borderM,
  '--ct-red': theme.red,
  '--ct-green': theme.green,
  '--ct-blue': theme.blue,
  '--ct-purple': theme.purple,
  '--ct-glass-bg': theme.glassBg,
  '--ct-glass-border': theme.glassBorder,
  '--ct-glass-blur': theme.blur,
  '--ct-glass-shadow': theme.shadow,
  '--ct-scrim': theme.scrim,
  '--ct-text-shadow': theme.textShadow,
  '--ct-orb-a': theme.orbA,
  '--ct-orb-b': theme.orbB,
  '--ct-orb-opacity': '0.5',
});

export const useTimeBasedTheme = () => {
  const [theme, setTheme] = useState(getSelectedTheme());

  useEffect(() => {
    const handleStorageChange = () => setTheme(getSelectedTheme());
    window.addEventListener('themeChanged', handleStorageChange);
    return () => window.removeEventListener('themeChanged', handleStorageChange);
  }, []);

  return theme;
};
